### PR TITLE
New Setting: Preserve manual User assignments.

### PR DESCRIPTION
**Pull request by gnat**
When Users are manually assigned to a group managed by autogroup, preserve these assignments when autogroups are automatically updated (other Users added, removed).

### CODE REVIEW

**Comment by gnat** [comment]
@emmarichardson If this looks good to you, feel free to merge it in. We release this code as public domain.

**Comment by gnat** [comment]
Thank you for your review @ak4t0sh I've made the changes.
This should now be ready for you. @emmarichardson

**Comment by emmarichardson** [comment]
So I am confused - if you turn off the groups setting, doesn't this accomplish the same thing?

**Comment by senaiboy** [comment]
> So I am confused - if you turn off the groups setting, doesn't this accomplish the same thing?

If I understand it right, this might solve our problem discussed a while ago with users belonging to more than one group. Eg Groups can have 'permanent' members (teachers) and temporary members (students). As students change group, Autogroup plugin will move them into their new group accordingly, while the teachers remain in these groups.

Turning off auto-update setting (presumably this is what you're referring to?) means students will remain in their old group as well as in the new groups.

Turning on auto-update (currently) only allow teachers to be in 1 group.

**Comment by gnat** [comment]
> With this new feature, we could have both the convenience of auto-updating members of a group as well as assigning permanent members to it.

@senaiboy yup, you've got it. This use case is the exact reason this was developed. 

It's intuitive because Users who have been manually assigned, remain manual. Users automatically assigned, remain automatic.

**Comment by emmarichardson** [comment]
@ak4t0sh Could you review the changes and let me know if it looks good?  Then I will merge.

**Comment by emmarichardson** [comment]
I think that the way it works is the intended use case.  From what I understand, it is so that they can add teachers to multiple groups, for example.  Seeing as it is an optional setting, I see no issue with it as long as we have no concerns about database/code confusion.  For example, does the setting automatically uncheck the groups setting that looks for changes in the group and updates if need be...I haven't had time to test it fully.

**Comment by ak4t0sh** [comment]
@emmarichardson if you are OK with this behaviour you can merge :)

**Pull request merged**
