### PR TITLE
Fix issue #38

### PR DESCRIPTION
**Pull request by Kemmotar83**
Fix issue #38

### CODE REVIEW

**Comment by Kemmotar83** [comment]
Hi @emmarichardson and @ak4t0sh ,

let me know if this fix works or there's anything to edit.

Giorgio

**Comment by emmarichardson** [comment]
Ok, back from Mexico - work has slowed down ever so slightly - my testing showed no issues.  @ak4t0sh Have you had a chance to review?

**Comment by ak4t0sh** [comment]
sorry for the late answer.
Not tested but seems good to me.

**Comment by emmarichardson** [comment]
Thanks will merge tomorrow

Emma Richardson
Distance Learning Coordinator
719-771-4022
Need to visit? Click below to schedule an appointment.
https://calendar.app.google/vy9C7FEp2GCNQrbE7

**Comment by emmarichardson** [comment]
I have merged this pull request.   I will be testing the next pull request tomorrow and will most probably merge that one before updating plugins database.

**Pull request merged**
