### PR TITLE
Fix filter issues

### PR DESCRIPTION
**Pull request by izendegi**
Applying filters in two places to fix multilang issues

### CODE REVIEW

**Comment by ak4t0sh** [comment]
Thanks your sharing! And sorry for the late answer.
I'll try to test your changes next week but it looks good to me :)

**Comment by emmarichardson** [comment]
@ak4t0sh Have you had a chance to review this?

**Comment by ak4t0sh** [comment]
hi yes review is OK but did not have time to test it. If your tests are OK you can merge it

**Comment by emmarichardson** [comment]
@izendegi If you could resolve the conflicts since some recent merges, I could get this pull request merged too.  Thanks.

**Pull request merged**
