### PR TITLE
Fix #16 default group by

### LINKED ISSUE #16: Group by default is unexpected
When an auto group is edited, the Group by field always defaults to the custom profile field that was created first. The expected behavior is that the Group by setting would default to the profile field that is being used by that group. IF the user is not paying much attention, they could actually change the profile field without realizing. Let me know if you need any additional clarification.

Geoff Brewster
geoffrey.brewster@ethinkeducation.com

### PR DESCRIPTION
**Pull request by luukverhoeven**
- array_merge doesn't respect array keys
- fix autogroup_set sortmodule if field is an custom profile field

### CODE REVIEW

**Comment by gemguardian** [comment]
ping @emmarichardson :)

**Comment by emmarichardson** [comment]
@luukverhoeven I mentioned to Gemma that I have another pull request ahead of this that I never got merged because I did not get it tested.  I am testing pull request #13 today - if it tests ok, I will go ahead and merge it.  I will then need you to review to make sure that nothing in the first merge affects your PR...once you have confirmed that, I will test yours and get it merged.  Sorry it has been so slow - I tend to rely on @ak4t0sh way more than I should and I have been ridiculously busy with COVID to even look at these, as I am sure he has too!

**Comment by emmarichardson** [comment]
I have merged the other PR (#13).  Please check and make sure that your PR still is ready for testing.  Thanks.

**Comment by luukverhoeven** [comment]
@emmarichardson Thanks for your time. I validated the merged version and the patch still works correct 😃

**Comment by ak4t0sh** [comment]
sorry for the delay. I'll try to review this PR today

**Review by ak4t0sh — APPROVED** [review]
Thanks for the fix @luukverhoeven  !
@emmarichardson  it seems perfect for integration and ready for release (even release number have been increased to right version as we can not ensure backward compatibility !)

**Comment by emmarichardson** [comment]
Thanks for reviewing. I will get it merged today and update the plugin
database.

**Comment by emmarichardson** [comment]
Merged and updated to Moodle plugins database.  Thank you so much for the fix and the patience!

**Comment by gemguardian** [comment]
Thank you all!

**Comment by luukverhoeven** [comment]
👍

@ak4t0sh Thanks for the review! @emmarichardson Thanks for the merged and update.

**Pull request merged**
