### PR TITLE
use standard string manager to display sort module name

### LINKED ISSUE #2: Sort module display should use standard string manager
As suggested by Vladimir Miranovic in https://moodle.org/plugins/local_autogroup « user info field » introcuced in v2.3 should be renamed to « custom profile field » which is more understandable by users.

Sort module name are displayed by their classname. I think that the class should not be renamed to avoid confusion in code but a proper display using standard moodle string manager should be implemented. This way we could separate code and display and it would allow customization and translation using AMOS.

I’ll try to work on it when I’ll have free time.

### PR DESCRIPTION
**Pull request by ak4t0sh**
This PR fix #2
Ping me if you merge #3 before this one, I’ll rebase my branch.

### CODE REVIEW

**Comment by emmarichardson** [comment]
I am the Canada Moot this week but started looking at it a little yesterday.  Will try and finish up next week.

Emma Richardson
DL Coordinator
Direct: 719-775-4022

**Comment by emmarichardson** [comment]
So which should I merge first?  Or does it matter?

**Comment by ak4t0sh** [comment]
As you want. If you have conflicts during the second merge (I do not think it will happen) I’ll rebase my branch to fix it ;)

**Comment by ak4t0sh** [comment]
branch rebased :)

**Pull request merged**
